### ISSUE TITLE
need guidelines 

### ISSUE THREAD

**Issue by masudr4n4** [marcuspimenta/BesTV#1]
how can i download this app.can you pls add the process of installetion of the app in the read.me?
if you do that i will creat a logo for this projects without any cost.

**Comment by marcuspimenta** [comment]
Hi Maaudrana, 

Thanks for the interesting. I will do it as soon as possible. 
To run the app you must have a Android TV or you could install an Android emulator in your PC.
I will let you know when I have the README ready with the steps to install the app.

Thnaks.

**Comment by masudr4n4** [comment]
ok.i am waiting for that.

**Comment by marcuspimenta** [comment]
Hi Maaudrana, 

I am sending you the apk that you can install in your Android TV. 
Let me know if you have any issue.

Thanks.
[BesTV APK.zip](https://github.com/marcuspimenta/BesTV/files/2046145/BesTV.APK.zip)

**Comment by masudr4n4** [comment]
Can not install this apk.showing this error.

![screenshot_2018-05-29-16-11-57](https://user-images.githubusercontent.com/34313493/40662953-7ee88948-6379-11e8-8c24-3e031e8a2eec.png)

**Comment by marcuspimenta** [comment]
Hi Maaudrana, 

You can't install this app in your mobile phone. 
This can be installed only in an Android TV.

**Comment by masudr4n4** [comment]
ohh my bad.sorry !
now can i make a logo for this?

**Comment by marcuspimenta** [comment]
Hi Maaudrana,

Yes. Think in some ideas. When you have some mock ready let me know and we could talk
about that. Just to let you know, I don't intent to get money with this app, it is an open source 
project, but I would like to publish in the Google Play. If you make the logo, I would add you 
in the project contributors.

**Comment by maaudrana** [comment]
I make a 3 logo for your project.. plz tell me which logo you need... 
![besttv-01](https://user-images.githubusercontent.com/34313493/40797217-3231f042-6529-11e8-8c80-1fd60b67710a.jpg)
